" VIM configuration - jeanbaptistem

" Activation de pathogen
call pathogen#infect()

" Charge la config par default de vim
source /etc/vim/vimrc

" Annule la compatibilite avec l’ancetre Vi
set nocompatible

" -- Affichage
set title                   " Met a jour le titre de votre fenetre ou de
                            " votre terminal
set number                  " Affiche le numero des lignes
set ruler                   " Affiche la position actuelle du curseur
set wrap                    " Affiche les lignes trop longues sur plusieurs
                            " lignes
set scrolloff=3             " Affiche un minimum de 3 lignes autour du curseur
                            " (pour le scroll)

" -- Recherche
set ignorecase              " Ignore la casse lors d’une recherche
set smartcase               " Si une recherche contient une majuscule,
                            " re-active la sensibilite a la casse
set incsearch               " Surligne les resultats de recherche pendant la
                            " saisie
set hlsearch                " Surligne les resultats de recherche
set path+=**                " Permet la recherche dans les sous dossiers

" -- Beep
set visualbell              " Empeche Vim de beeper
set noerrorbells            " Empeche Vim de beeper

" Active le comportement ’habituel’ de la touche retour en arriere
set backspace=indent,eol,start

" Cache les fichiers lors de l’ouverture d’autres fichiers
set hidden

" -- Coloration syntaxique
syntax on                    " Active la coloration syntaxique
filetype plugin indent on
colorscheme monokai          " Utilise monokai comme color scheme
set background=dark

" -- Plugins


" -- Key maping
let mapleader=","
